# This workflow only runs on release
# and when test-lint.yml is successful
name: Release library

on:
  workflow_run:
    # Run after "Test and lint" workflow
    workflows: ['Test and lint']
    types:
      - completed # Only when it's completed

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Print workflow_run event contents and github.ref
        run: |
            echo "github.event.workflow_run.conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "github.ref: ${{ github.ref }}"
  
  publish-lib:
    # Only proceed if the tests passed and we're on release
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run release
        run: |
            echo "Run Test and Release"
